组件
CyclejsCN/cyclejs.cn pull request #21
Opened 2017-07-20 05:32 UTC by yoyoyohamapi

@JasinYip

2017-07-20 13:10 UTC, Weiting-Zhang commented on content/documentation/components.md
> +UI 通常由许多可重用的元素组成：按钮，图标，滑块，划过时拥有效果的头像，智能表单域等等。在包含 Cycle.js 在内的许多前端框架中，这些元素被称为组件。但在 Cycle.js 中，组件还具有一个特性。
图标 => 图表

2017-07-20 13:15 UTC, Weiting-Zhang commented on content/documentation/components.md
> +这个特性是什么意思呢？它意味着你可以构建一个应用程序，它简单到只是制作一个滑块组件。截止目前，我们知道了如何创建一个 Cycle.js `main()` 来制作一个智能滑块 widget。之后，由于 `main()` 仅只是一个函数，它从外部世界获得输入，并通过 return 来产出输出，在一个更大的 Cycle.js 应用中，我们只需要调用这个 `main()`，就能获得一个智能滑块。
这个特性是什么意思呢？ => 这是怎么做到的？

2017-07-20 13:21 UTC, Weiting-Zhang commented on content/documentation/components.md
> +这个特性是什么意思呢？它意味着你可以构建一个应用程序，它简单到只是制作一个滑块组件。截止目前，我们知道了如何创建一个 Cycle.js `main()` 来制作一个智能滑块 widget。之后，由于 `main()` 仅只是一个函数，它从外部世界获得输入，并通过 return 来产出输出，在一个更大的 Cycle.js 应用中，我们只需要调用这个 `main()`，就能获得一个智能滑块。
如果上面的改了，后面的「它意味着」也要改了。理解有差别XD

2017-07-20 14:09 UTC, Weiting-Zhang commented on content/documentation/components.md
> +为了更好的理解 Cycle.js 中的组件，我们干脆亲自做一个数据流组件，这个组件是一个简单的带标签的滑块。该滑块组件接收用户产生的事件作为输入，并产出一个滑块的虚 DOM 流。
「virtual DOM 」要不要翻译成我们常说的「虚拟 DOM」呢

2017-07-20 14:10 UTC, Weiting-Zhang commented on content/documentation/components.md
> +为了更好的理解 Cycle.js 中的组件，我们干脆亲自做一个数据流组件，这个组件是一个简单的带标签的滑块。该滑块组件接收用户产生的事件作为输入，并产出一个滑块的虚 DOM 流。
后面的英文是不是忘记翻译了XD

2017-07-20 14:13 UTC, Weiting-Zhang commented on content/documentation/components.md
> +- 滑块最小值
这里括号里的标点转换不一致

2017-07-20 14:24 UTC, Weiting-Zhang commented on content/documentation/components.md
> +> sources 和 sinks 是一个反例，因为二者扮演了某种特别的 sockets 的角色，这些 sockets 连接了组件和外部世界。sources 和 sinks 的名字仅只是作为设置或者获取流的 “键（keys）”。在 `run(main, drivers)` 语句中，这些 key 需要匹配 `drivers` 对象中的相同的 key。注意到，在 `drivers` 中，每一个由某个
「这些 key」&& 「相同的 key」中 key => keys

2017-07-20 14:35 UTC, Weiting-Zhang commented on content/documentation/components.md
> +> sources 和 sinks 是一个反例，因为二者扮演了某种特别的 sockets 的角色，这些 sockets 连接了组件和外部世界。sources 和 sinks 的名字仅只是作为设置或者获取流的 “键（keys）”。在 `run(main, drivers)` 语句中，这些 key 需要匹配 `drivers` 对象中的相同的 key。注意到，在 `drivers` 中，每一个由某个
「都不是」应该加重

2017-07-20 14:55 UTC, Weiting-Zhang commented on content/documentation/components.md
> +> sources 和 sinks 是一个反例，因为二者扮演了某种特别的 sockets 的角色，这些 sockets 连接了组件和外部世界。sources 和 sinks 的名字仅只是作为设置或者获取流的 “键（keys）”。在 `run(main, drivers)` 语句中，这些 key 需要匹配 `drivers` 对象中的相同的 key。注意到，在 `drivers` 中，每一个由某个
我觉得「注意到」后面的部分，原文强调了原因， （因为drivers 都是函数，那被 key 索引的 drivers 也是函数）译文省略掉了。
=> 观察为什么在这些 ，由某个 key 索引的 driver 都**不是**一个流。它们是函数，因为 drivers 都是函数。

2017-07-20 15:17 UTC, Weiting-Zhang commented on content/documentation/components.md
> +> 这也就是为什么我们不应该使用 `DOM$` 来命名 sink，在 `drivers` 对象中，`DOM` 对应的 driver 是 DOM Driver，该 driver 是一个函数。并且，在 `main` 函数中， `sources.DOM` 是一个 DOM Source 对象（而不是流），它具有 `select()` 和 `events()` 方法。
它具有 `select()` 和 `events()` 方法 => 它具有类似 `select()` 和 `events()` 的方法

2017-07-20 15:22 UTC, Weiting-Zhang commented on content/documentation/components.md
> +> 命名 sink 的时候，使用简单的 key 来命名就行了，不需要遵从流命名的管理来添加后缀 `$`。之后，我们可以通过类似 `const props$ = sources.props` 的方式来从 sources 中获得我们需要的流。
key => **key**

2017-07-20 15:24 UTC, Weiting-Zhang commented on content/documentation/components.md
> +现在，labeled slider 这个数据流组件已经整装待发了，我们可以在一个更大型的应用中使用它了。先让我们重命名这个组件为 `LabeledSlider`，以便于更大应用中的 `main()` 区分。
以便于 => 以便于与

2017-07-20 15:29 UTC, Weiting-Zhang commented on content/documentation/components.md
> +> 据此，大写命名法在使用了函数式编程的 JavaScript 中也变得可用。我们不需要认为大写的名词代表了类或者构造函数，在 Cycle.js 中，使用大写命名法命名数据流组件将会是约定俗成的惯例。我们会使用 `FooButton` 来命名数据流组件，其对应的驼峰命名法 `fooButton` 则用于命名该组件输出的 sink 对象。
要不要把举的栗子翻译过来啊。。这里忽略了一些，但是原本就挺好懂的，我也觉得挺好的…

2017-07-20 15:31 UTC, Weiting-Zhang commented on content/documentation/components.md
> +最原始的方式是调用两次 `LabeledSlider()`，一次传入体重需要的 props 来获得体重滑块，一次则是传入身高需要的 props 来获得身高滑块。
句尾的句号应改为冒号。
先review到这里吧有空再来☆彡

2017-07-20 15:35 UTC, Weiting-Zhang requested changes
好长好长。译者辛苦辣! 译文很棒哦，有些精简了原文，到底要不要完全完全保留原文呢觉得好纠结呀

2017-07-22 00:47 UTC, Weiting-Zhang commented on content/documentation/components.md
> +假定我们仅仅调用该函数来获得一个体重滑块。语句 `sources.DOM.select('.slider'` **会在整个 DOM 树中选择所有 ** `.slider` 元素。而我们的体重和身高组件的 css 类都是 `.slider`，因此，当我们滑动任意滑块时，两个滑块都会动。
「select('.slider' 」后面少了括号

2017-07-22 00:50 UTC, Weiting-Zhang commented on content/documentation/components.md
> +一个组件的输出不应当干扰其他组件，一个组件也不应当受到其他组件输出的干扰。为了保持 `一个组件仅只是一个 Cycle.js 应用` 这个性质，我们还需要实现下面两个性质：
受到其他组件的干扰 => 受到其他兄弟组件的干扰

2017-07-22 00:52 UTC, Weiting-Zhang commented on content/documentation/components.md
> +一个组件的输出不应当干扰其他组件，一个组件也不应当受到其他组件输出的干扰。为了保持 `一个组件仅只是一个 Cycle.js 应用` 这个性质，我们还需要实现下面两个性质：
「为了保持」后面的引号换错了，不是代码块

2017-07-22 00:58 UTC, Weiting-Zhang commented on content/documentation/components.md
> +对于 DOM source 和 DOM sink，我们可以使用一个唯一标识符来作为每个虚 DOM 元素的名字空间。首先，我们会为 DOM sink 打个补丁，该流发出的 VNode 会被添加额外的类名：
「名字空间」=> 命名空间

2017-07-22 00:59 UTC, Weiting-Zhang commented on content/documentation/components.md
> +对于 DOM source 和 DOM sink，我们可以使用一个唯一标识符来作为每个虚 DOM 元素的名字空间。首先，我们会为 DOM sink 打个补丁，该流发出的 VNode 会被添加额外的类名：
「VNode」=> VNodes

2017-07-22 01:01 UTC, Weiting-Zhang commented on content/documentation/components.md
> +滑动体重滑块时，即执行 `sources.DOM.select('.slider').events('input')` 时，只应该 `<div class="labeled-slider weight">` 及其子孙元素上检测用户用户事件。
「只应该」=> 「只应该在」

2017-07-22 01:08 UTC, Weiting-Zhang commented on content/documentation/components.md
>  >
「`DOM source`」 => "DOM source"

2017-07-22 01:18 UTC, Weiting-Zhang commented on content/documentation/components.md
> +> `select('.foo').select('.bar').events('click')` 返回了一个发生在 `'.foo .bar'` 元素上的点击事件流。`select('.foo')` “收窄” DOM source 的 scope，让我们在更深一层 DOM source 上去寻找点击流。
「"收窄"」=> ”收窄”
中英标点差异

2017-07-22 01:21 UTC, Weiting-Zhang commented on content/documentation/components.md
> +这正是函数 [`isolate()`](https://github.com/cyclejs/cyclejs/tree/master/isolate) （`npm install @cycle/isolate`）的由来。该函数内部调用了 `isolateSource` 和 `isolateSink` 。`isolate(Component, scope)` 接受一个数据流组件 `Componen
「代码片」=> 代码片段 or  代码块

2017-07-22 01:30 UTC, Weiting-Zhang commented on content/documentation/components.md
> +为了实现组件的可重用性，**任何 Cycle.js 组件都只是一个函数，这个函数可以被用在任何的更大的 Cycle.js 应用中**。sources 和 sinks 是应用和 driver 间的接口，同时也是子组件及其父组件间的接口。
「source」首字母大写

2017-07-22 04:17 UTC, yoyoyohamapi commented on content/documentation/components.md
> +这个特性是什么意思呢？它意味着你可以构建一个应用程序，它简单到只是制作一个滑块组件。截止目前，我们知道了如何创建一个 Cycle.js `main()` 来制作一个智能滑块 widget。之后，由于 `main()` 仅只是一个函数，它从外部世界获得输入，并通过 return 来产出输出，在一个更大的 Cycle.js 应用中，我们只需要调用这个 `main()`，就能获得一个智能滑块。
@Weiting-Zhang how is that so? 是缘何、为何的意思，这里 staltz 也没有说明这个特性的原理，只是在阐述特性的含义和优势

2017-07-22 04:38 UTC, yoyoyohamapi commented on content/documentation/components.md
> +为了实现组件的可重用性，**任何 Cycle.js 组件都只是一个函数，这个函数可以被用在任何的更大的 Cycle.js 应用中**。sources 和 sinks 是应用和 driver 间的接口，同时也是子组件及其父组件间的接口。
@Weiting-Zhang 应该按照中文语法来吧？

2017-07-22 04:39 UTC, Weiting-Zhang commented on content/documentation/components.md
> +> 据此，大写命名法在使用了函数式编程的 JavaScript 中也变得可用。我们不需要认为大写的名词代表了类或者构造函数，在 Cycle.js 中，使用大写命名法命名数据流组件将会是约定俗成的惯例。我们会使用 `FooButton` 来命名数据流组件，其对应的驼峰命名法 `fooButton` 则用于命名该组件输出的 sink 对象。
忽略这条吧看错了囧rz

2017-07-22 05:00 UTC, Weiting-Zhang commented on content/documentation/components.md
> +为了实现组件的可重用性，**任何 Cycle.js 组件都只是一个函数，这个函数可以被用在任何的更大的 Cycle.js 应用中**。sources 和 sinks 是应用和 driver 间的接口，同时也是子组件及其父组件间的接口。
嗯ok

2017-07-22 11:54 UTC, JasinYip reviewed
额，貌似我之前的 review 变成 outdated 的了……

2017-07-22 11:54 UTC, JasinYip commented on content/documentation/components.md
> +UI 通常由许多可重用的元素组成：按钮，图标，滑块，划过时拥有效果的头像，智能表单域等等。在包含 Cycle.js 在内的许多前端框架中，这些元素被称为组件。但在 Cycle.js 中，组件还具有一个特性。
「按钮，图标，滑块」应该用顿号「按钮、图标、滑块」，包括后面的～

2017-07-22 11:54 UTC, JasinYip commented on content/documentation/components.md
> +这个特性是什么意思呢？它意味着你可以构建一个应用程序，它简单到只是制作一个滑块组件。截止目前，我们知道了如何创建一个 Cycle.js `main()` 来制作一个智能滑块 widget。之后，由于 `main()` 仅只是一个函数，它从外部世界获得输入，并通过 return 来产出输出，在一个更大的 Cycle.js 应用中，我们只需要调用这个 `main()`，就能获得一个智能滑块。
「智能滑块 widget」中的 `widget` 可以翻译成「组件」吧？

2017-07-22 11:54 UTC, JasinYip commented on content/documentation/components.md
> +这个特性是什么意思呢？它意味着你可以构建一个应用程序，它简单到只是制作一个滑块组件。截止目前，我们知道了如何创建一个 Cycle.js `main()` 来制作一个智能滑块 widget。之后，由于 `main()` 仅只是一个函数，它从外部世界获得输入，并通过 return 来产出输出，在一个更大的 Cycle.js 应用中，我们只需要调用这个 `main()`，就能获得一个智能滑块。
「并通过 return 来产出输出，在一个更大的 」这里面这个逗号是不是用句号更合适？

2017-07-22 11:54 UTC, JasinYip commented on content/documentation/components.md
> +- 滑块最小值
逗号应该要换顿号吧？

2017-07-22 11:54 UTC, JasinYip commented on content/documentation/components.md
> +> sources 和 sinks 是一个反例，因为二者扮演了某种特别的 sockets 的角色，这些 sockets 连接了组件和外部世界。sources 和 sinks 的名字仅只是作为设置或者获取流的 “键（keys）”。在 `run(main, drivers)` 语句中，这些 key 需要匹配 `drivers` 对象中的相同的 key。注意到，在 `drivers` 中，每一个由某个
中文翻译不用复数～

2017-07-24 11:49 UTC, merged