Translate: HTML for #10
CyclejsCN/cyclejs.cn pull request #27
Opened 2017-07-24 09:44 UTC by jeasonstudio

checkout 出分支，重新设置了head解决了这个问题

2017-07-26 07:40 UTC, ZexuanTHU requested changes
几点校对意见，修改后似更妥，谢谢！

2017-07-26 07:40 UTC, ZexuanTHU commented on content/api/html.md
> +参数为回调函数 `effect` 和 `options` 对象，driver 的输入可以是一个虚拟 DOM 对象，也就是 `Snabbdom VNode` 对象，输出为一个 `DOMSource`：方法 select() 和 events() 查询到的 Observables 集合。
> ，driver 的输入可以是一个虚拟对象，也就是 `Snabbdom VNode` 对象

=>
 
> 。driver 的输入为一个虚拟 DOM 对象流，也就是 Snabbdom 中的 "VNode" 对象

注：如上所指，本句开头的逗号应改为句号。

2017-07-26 07:40 UTC, ZexuanTHU commented on content/api/html.md
> +HTML Driver 是对 DOM Driver 的完善。不同于在 DOM 上直接生成 elements，它会生成 HTML 字符串，并对这些字符串产生副作用，回调函数 `effect` 则是用于描述或自定义这些副作用。所以说，如果你希望将 HTML Driver 用于服务端渲染后发送到客户端（这是 HTML Driver 的典型用法），你需要在参数 `effect` 函数中写一些类似 `ht
> 你需要在参数 `effect` 函数中写一些类似 `html => response.send(html)` 的部分。这么做，HTML Driver 就会知道渲染的 HTML 字符串会产生什么副作用。

=>

> 你需要传递一些类似于 `html => response.send(html)` 的函数作为 `effect` 参数。由此，HTML Driver 就能获知应对其刚刚渲染产生的 HTML 字符串施以何种副作用。

2017-07-26 07:40 UTC, ZexuanTHU commented on content/api/html.md
> +HTML Driver 仅对回调函数 `effect` 中的副作用有效，它可以被认为是一个 `sink-only driver` 。但是，为了在服务端渲染时能完美代替 DOM Driver HTML Driver 返回一个类似 `DOMSource` 的源对象。这将有助于我们把已有的用 DOM Driver 的应用程序迁移到 HTML Driver。由于在服务端没有用户事件，所以在你查询时虚拟的
> 这将有助于我们把已有的用 DOM Driver 的应用程序迁移到 HTML Driver。

=>

> 这将有助于我们复用为 DOM Driver 编写的应用程序。

2017-07-26 07:40 UTC, ZexuanTHU commented on content/api/html.md
> +HTML Driver 仅对回调函数 `effect` 中的副作用有效，它可以被认为是一个 `sink-only driver` 。但是，为了在服务端渲染时能完美代替 DOM Driver HTML Driver 返回一个类似 `DOMSource` 的源对象。这将有助于我们把已有的用 DOM Driver 的应用程序迁移到 HTML Driver。由于在服务端没有用户事件，所以在你查询时虚拟的
> 但是，为了在服务端渲染时能完美代替 DOM Driver

句末逗号缺失。

2017-07-26 07:40 UTC, ZexuanTHU commented on content/api/html.md
> +`DOMSource.select(selector)` 返回一个新的 `DOMSource` ，其范围受限于与给定的 CSS 选择器匹配的元素。
> 其范围受限于与给定的 CSS 选择器匹配的元素。

=>

> 其作用域限于与给定的 CSS 选择器匹配的元素。

2017-07-26 07:40 UTC, ZexuanTHU commented on content/api/html.md
> +`DOMSource.events(eventType, options)` 返回空数据流。如果你使用 `@cycle/xstream-run` 搭配 HTML Driver 来启动你的应用，它返回的是一个 *xstream* 数据流；或者使用 `@cycle/rxjs-run` 启动应用，那你将得到一个 `RxJS Observable`。
> 它返回的是一个 *xstream* 数据流

=>

> 它返回的是一个 **xstream** 数据流

注：中文文档中斜体字样使用加粗字体代替

2017-07-26 07:40 UTC, ZexuanTHU commented on content/api/html.md
> +参数为回调函数 `effect` 和 `options` 对象，driver 的输入可以是一个虚拟 DOM 对象，也就是 `Snabbdom VNode` 对象，输出为一个 `DOMSource`：方法 select() 和 events() 查询到的 Observables 集合。
> 输出为一个 `DOMSource`

=> 

> 输出为一个 DOMSource

2017-07-26 07:40 UTC, ZexuanTHU commented on content/api/html.md
> +HTML Driver 仅对回调函数 `effect` 中的副作用有效，它可以被认为是一个 `sink-only driver` 。但是，为了在服务端渲染时能完美代替 DOM Driver HTML Driver 返回一个类似 `DOMSource` 的源对象。这将有助于我们把已有的用 DOM Driver 的应用程序迁移到 HTML Driver。由于在服务端没有用户事件，所以在你查询时虚拟的
> `sink-only driver` 
> `DOMSource` （出现 2 次）

=>

> sink-only driver
> DOMSource

2017-07-26 07:40 UTC, ZexuanTHU commented on content/api/html.md
> +`DOMSource.select(selector)` 返回一个新的 `DOMSource` ，其范围受限于与给定的 CSS 选择器匹配的元素。
同上，`DOMSource` => DOMSource。

2017-07-26 07:40 UTC, ZexuanTHU commented on content/api/html.md
> +`DOMSource.events(eventType, options)` 返回空数据流。如果你使用 `@cycle/xstream-run` 搭配 HTML Driver 来启动你的应用，它返回的是一个 *xstream* 数据流；或者使用 `@cycle/rxjs-run` 启动应用，那你将得到一个 `RxJS Observable`。
`RxJS Observable` => RxJs Observable

2017-07-26 07:40 UTC, ZexuanTHU commented on content/api/html.md
> +`DOMSource.elements()` 返回根据你虚拟 DOM 渲染出的 HTML 字符串。
> 返回根据你虚拟 DOM 渲染出的 HTML 字符串。

=>

> 返回依据你的sink接口虚拟 DOM 流渲染的 HTML 字符串流。

2017-07-26 07:40 UTC, ZexuanTHU commented on content/api/html.md
> +- `options: HTMLDriverOptions` 对象，含有一个可选属性：`transposition: boolean` ，启用/禁用虚拟 DOM 树中内部的转换。
> 启用/禁用虚拟 DOM 树中内部的转换。

=>

> 用以启用/禁用虚拟 DOM 树内部数据流的转换。

2017-07-26 07:40 UTC, ZexuanTHU commented on content/api/html.md
> +*(Function)* HTML driver 函数。该函数期望将 VNode 流作为输入，并输出 DOMSource 对象。
> *(Function)* HTML driver 函数。该函数期望将 VNode 流作为输入，并输出 DOMSource 对象。

=>

> **(Function)** HTML driver 函数，该函数接收 VNode 流作为输入，并输出 DOMSource 对象。

2017-07-26 07:40 UTC, ZexuanTHU commented on content/api/html.md
> +- `effect: Function` 回调函数，它将一段渲染为 HTML 后的字符串作为输入，起到一些副作用，不返回任何值。
> `effect: Function` 回调函数，它将一段渲染为 HTML 后的字符串作为输入，起到一些副作用，不返回任何值。

=>

> `effect: Function` 回调函数，它接收一段已渲染的 HTML 串作为输入，并对其产生一些副作用，不返回任何值。

2017-07-26 07:40 UTC, ZexuanTHU commented on content/api/html.md
> +Cycle.js driver 用于将虚拟 DOM 流渲染为 HTML 。它基于 DOM driver 和 [snabbdom](https://github.com/paldepind/snabbdom/)，并将意图用于服务端渲染，其与客户端渲染等效。
> 并将意图用于服务端渲染，其与客户端渲染等效。

=>

> 其适用于在服务器端渲染 HTML，与此相对，DOM driver 将在客户端进行渲染。

2017-07-26 07:40 UTC, ZexuanTHU commented on content/api/html.md
> +*(Function)* HTML driver 函数。该函数期望将 VNode 流作为输入，并输出 DOMSource 对象。
> *(Function)* HTML driver 函数。该函数期望将 VNode 流作为输入，并输出 DOMSource 对象。

=>

> **(Function)** HTML driver 函数。该函数接收 VNode 流作为输入，并输出 DOMSource 对象。

2017-08-09 03:17 UTC, jeasonstudio commented
@ZexuanTHU 感谢你的认真校对，我已经做了修改。
十分抱歉，最近一直忙于写业务，没有花时间到开源社区。
@JasinYip

2017-08-14 03:09 UTC, ZexuanTHU commented
@JasinYip 校对及修改均已完成，是否可以合并？

2017-08-14 03:11 UTC, ZexuanTHU commented
@jeasonstudio 一点微小的贡献 :) (苟......

2017-08-15 01:45 UTC, merged